// Account Summary
export const SEARCH_ACCOUNT_SUMMARY = 'SEARCH_ACCOUNT_SUMMARY';
export const SEARCH_ACCOUNT_SUMMARY_PENDING = 'SEARCH_ACCOUNT_SUMMARY_PENDING';
export const SEARCH_ACCOUNT_SUMMARY_FULFILLED = 'SEARCH_ACCOUNT_SUMMARY_FULFILLED';
export const SEARCH_ACCOUNT_SUMMARY_REJECTED = 'SEARCH_ACCOUNT_SUMMARY_REJECTED';
export const PRINT_ACCOUNT_SUMMARY = 'PRINT_ACCOUNT_SUMMARY';

// Portfolio Summary
export const GET_ACCOUNT_LIST = 'GET_ACCOUNT_LIST';
export const GET_ACCOUNT_LIST_PENDING = 'GET_ACCOUNT_LIST_PENDING';
export const GET_ACCOUNT_LIST_FULFILLED = 'GET_ACCOUNT_LIST_FULFILLED';
export const GET_ACCOUNT_LIST_REJECTED = 'GET_ACCOUNT_LIST_REJECTED';

export const SEARCH_PORTFOLIO_FUND_SUMMARY = 'SEARCH_PORTFOLIO_FUND_SUMMARY';
export const SEARCH_PORTFOLIO_FUND_SUMMARY_PENDING = 'SEARCH_PORTFOLIO_FUND_SUMMARY_PENDING';
export const SEARCH_PORTFOLIO_FUND_SUMMARY_FULFILLED = 'SEARCH_PORTFOLIO_FUND_SUMMARY_FULFILLED';
export const SEARCH_PORTFOLIO_FUND_SUMMARY_REJECTED = 'SEARCH_PORTFOLIO_FUND_SUMMARY_REJECTED';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_PENDING = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_PENDING';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_FULFILLED = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_FULFILLED';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_REJECTED = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_REJECTED';

export const PRINT_PORTFOLIO_SUMMARY = 'PRINT_PORTFOLIO_SUMMARY';

// Transaction History
export const GET_FUND_LIST = 'GET_FUND_LIST';
export const GET_FUND_LIST_PENDING = 'GET_FUND_LIST_PENDING';
export const GET_FUND_LIST_FULFILLED = 'GET_FUND_LIST_FULFILLED';
export const GET_FUND_LIST_REJECTED = 'GET_FUND_LIST_REJECTED';
export const GET_DEPOSIT_LIST = 'GET_DEPOSIT_LIST';
export const GET_DEPOSIT_LIST_PENDING = 'GET_DEPOSIT_LIST_PENDING';
export const GET_DEPOSIT_LIST_FULFILLED = 'GET_DEPOSIT_LIST_FULFILLED';
export const GET_DEPOSIT_LIST_REJECTED = 'GET_DEPOSIT_LIST_REJECTED';

export const SEARCH_FUND_TRANSACTION_HISTORY = 'SEARCH_FUND_TRANSACTION_HISTORY';
export const SEARCH_FUND_TRANSACTION_HISTORY_PENDING = 'SEARCH_FUND_TRANSACTION_HISTORY_PENDING';
export const SEARCH_FUND_TRANSACTION_HISTORY_FULFILLED = 'SEARCH_FUND_TRANSACTION_HISTORY_FULFILLED';
export const SEARCH_FUND_TRANSACTION_HISTORY_REJECTED = 'SEARCH_FUND_TRANSACTION_HISTORY_REJECTED';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY_PENDING = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY_PENDING';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY_FULFILLED = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY_FULFILLED';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY_REJECTED = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY_REJECTED';

export const PRINT_TRANSACTION_HISTORY = 'PRINT_TRANSACTION_HISTORY';
