// ------------------------------------------------
// common Actions
// ------------------------------------------------
export const GET_ASSET_TYPE_LIST = 'GET_ASSET_TYPE_LIST';
export const GET_ASSET_TYPE_LIST_PENDING = 'GET_ASSET_TYPE_LIST_PENDING';
export const GET_ASSET_TYPE_LIST_FULFILLED = 'GET_ASSET_TYPE_LIST_FULFILLED';
export const GET_ASSET_TYPE_LIST_REJECTED = 'GET_ASSET_TYPE_LIST_REJECTED';
export const GET_BUY_SELL_LIST = 'GET_BUY_SELL_LIST';
export const GET_BUY_SELL_LIST_PENDING = 'GET_BUY_SELL_LIST_PENDING';
export const GET_BUY_SELL_LIST_FULFILLED = 'GET_BUY_SELL_LIST_FULFILLED';
export const GET_BUY_SELL_LIST_REJECTED = 'GET_BUY_SELL_LIST_REJECTED';

// ------------------------------------------------
// Account Summary Actions
// ------------------------------------------------
// (1) Account Summary
export const SEARCH_ACCOUNT_SUMMARY = 'SEARCH_ACCOUNT_SUMMARY';
export const SEARCH_ACCOUNT_SUMMARY_PENDING = 'SEARCH_ACCOUNT_SUMMARY_PENDING';
export const SEARCH_ACCOUNT_SUMMARY_FULFILLED = 'SEARCH_ACCOUNT_SUMMARY_FULFILLED';
export const SEARCH_ACCOUNT_SUMMARY_REJECTED = 'SEARCH_ACCOUNT_SUMMARY_REJECTED';
export const PRINT_ACCOUNT_SUMMARY = 'PRINT_ACCOUNT_SUMMARY';

// (2) Portfolio Summary
export const GET_ACCOUNT_LIST = 'GET_ACCOUNT_LIST';
export const GET_ACCOUNT_LIST_PENDING = 'GET_ACCOUNT_LIST_PENDING';
export const GET_ACCOUNT_LIST_FULFILLED = 'GET_ACCOUNT_LIST_FULFILLED';
export const GET_ACCOUNT_LIST_REJECTED = 'GET_ACCOUNT_LIST_REJECTED';

export const SEARCH_PORTFOLIO_FUND_SUMMARY = 'SEARCH_PORTFOLIO_FUND_SUMMARY';
export const SEARCH_PORTFOLIO_FUND_SUMMARY_PENDING = 'SEARCH_PORTFOLIO_FUND_SUMMARY_PENDING';
export const SEARCH_PORTFOLIO_FUND_SUMMARY_FULFILLED = 'SEARCH_PORTFOLIO_FUND_SUMMARY_FULFILLED';
export const SEARCH_PORTFOLIO_FUND_SUMMARY_REJECTED = 'SEARCH_PORTFOLIO_FUND_SUMMARY_REJECTED';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_PENDING = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_PENDING';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_FULFILLED = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_FULFILLED';
export const SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_REJECTED = 'SEARCH_PORTFOLIO_DEPOSIT_SUMMARY_REJECTED';

export const PRINT_PORTFOLIO_SUMMARY = 'PRINT_PORTFOLIO_SUMMARY';

// (3) Transaction History
export const GET_FUND_LIST = 'GET_FUND_LIST';
export const GET_FUND_LIST_PENDING = 'GET_FUND_LIST_PENDING';
export const GET_FUND_LIST_FULFILLED = 'GET_FUND_LIST_FULFILLED';
export const GET_FUND_LIST_REJECTED = 'GET_FUND_LIST_REJECTED';
export const GET_DEPOSIT_LIST = 'GET_DEPOSIT_LIST';
export const GET_DEPOSIT_LIST_PENDING = 'GET_DEPOSIT_LIST_PENDING';
export const GET_DEPOSIT_LIST_FULFILLED = 'GET_DEPOSIT_LIST_FULFILLED';
export const GET_DEPOSIT_LIST_REJECTED = 'GET_DEPOSIT_LIST_REJECTED';

export const SEARCH_FUND_TRANSACTION_HISTORY = 'SEARCH_FUND_TRANSACTION_HISTORY';
export const SEARCH_FUND_TRANSACTION_HISTORY_PENDING = 'SEARCH_FUND_TRANSACTION_HISTORY_PENDING';
export const SEARCH_FUND_TRANSACTION_HISTORY_FULFILLED = 'SEARCH_FUND_TRANSACTION_HISTORY_FULFILLED';
export const SEARCH_FUND_TRANSACTION_HISTORY_REJECTED = 'SEARCH_FUND_TRANSACTION_HISTORY_REJECTED';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY_PENDING = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY_PENDING';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY_FULFILLED = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY_FULFILLED';
export const SEARCH_DEPOSIT_TRANSACTION_HISTORY_REJECTED = 'SEARCH_DEPOSIT_TRANSACTION_HISTORY_REJECTED';

export const PRINT_TRANSACTION_HISTORY = 'PRINT_TRANSACTION_HISTORY';

// ------------------------------------------------
// Order Pad Actions
// ------------------------------------------------
export const GET_FUND_DETAILS_LIST = 'GET_FUND_DETAILS_LIST';
export const GET_FUND_DETAILS_LIST_PENDING = 'GET_FUND_DETAILS_LIST_PENDING';
export const GET_FUND_DETAILS_LIST_FULFILLED = 'GET_FUND_DETAILS_LIST_FULFILLED';
export const GET_FUND_DETAILS_LIST_REJECTED = 'GET_FUND_DETAILS_LIST_REJECTED';
export const GET_PAYMENT_DETAILS_LIST = 'GET_PAYMENT_DETAILS_LIST';
export const GET_PAYMENT_DETAILS_LIST_PENDING = 'GET_PAYMENT_DETAILS_LIST_PENDING';
export const GET_PAYMENT_DETAILS_LIST_FULFILLED = 'GET_PAYMENT_DETAILS_LIST_FULFILLED';
export const GET_PAYMENT_DETAILS_LIST_REJECTED = 'GET_PAYMENT_DETAILS_LIST_REJECTED';
export const ADD_ORDER = 'ADD_ORDER';
export const ADD_ORDER_PENDING = 'ADD_ORDER_PENDING';
export const ADD_ORDER_FULFILLED = 'ADD_ORDER_FULFILLED';
export const ADD_ORDER_REJECTED = 'ADD_ORDER_REJECTED';

// ----------------------------------------------------------
// EPDS Actions
// ----------------------------------------------------------
export const SEARCH_EPDS = 'SEARCH_EPDS';
export const SEARCH_EPDS_PENDING = 'SEARCH_EPDS_PENDING';
export const SEARCH_EPDS_FULFILLED = 'SEARCH_EPDS_FULFILLED';
export const SEARCH_EPDS_REJECTED = 'SEARCH_EPDS_REJECTED';

export const GET_EPDS_DOC = 'GET_EPDS_DOC';
export const GET_EPDS_DOC_PENDING = 'GET_EPDS_DOC_PENDING';
export const GET_EPDS_DOC_FULFILLED = 'GET_EPDS_DOC_FULFILLED';
export const GET_EPDS_DOC_REJECTED = 'GET_EPDS_DOC_REJECTED';

